"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./query-provider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CartProvider from "./context/CartContext";
import WishlistProvider from "./context/WishListContext";
import ProfileProvider from "./context/ProfileContext";
import ReadyDesignCartProvider from "./context/ReadyDesignCartContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <WishlistProvider>
            <ProfileProvider>
              <ReadyDesignCartProvider>
                <Navbar />
                <QueryProvider>
                  {children}
                  <Footer />
                </QueryProvider>
              </ReadyDesignCartProvider>
            </ProfileProvider>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
